### ISSUE TITLE
Lineas 71-73 error al codificar

### ISSUE THREAD

**Issue by germanarcos** [ericmoros/Desarrollo-web#1]
short underCoded = (short) ((foundChar -inputNum) - 65);
					generatedText += (char) (91 + underCoded);

**Comment by ericmoros** [comment]
Solucionado!! 💯
https://github.com/ericmoros/Desarrollo-web/blob/master/Programaci%C3%B3n/Tema%20-%2004/Java/Hoja%20-%204/Ej%20-%2008/src/H4_Ej8.java

Muchas gracias
